import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ReactQueryProvider from "@/providers/react-query";

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="montserrat">
      <body className="bg-[#0a0a0a]">
        <ReactQueryProvider>
          {children}
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
